### ISSUE TITLE
개발환경 세팅

### ISSUE THREAD

**Issue by ghk829** [ghk829/KangisMarket#1]
@samslow 
1. Vuejs 개발환경 setting

2. github commit message 작성하는 법 알아오기

**Comment by ghk829** [comment]
왠만하면 eclipse로 개발하자용~

**Comment by samslow** [comment]
VsCode로할건데~

**Comment by ghk829** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ github만 연동되면 된다^^ ㅎㅎㅎㅎㅎ
