### ISSUE TITLE
BenchMark Site 및 Bootstrap 테마

### ISSUE THREAD

**Issue by ghk829** [ghk829/KangisMarket#2]
1. 이거 경매면 옥션 이런거 따라가면 되지 않냐?

2. 테마 생각 좀 해보삼. 나는 다크하게 가는 게 나을듯

**Comment by samslow** [comment]
1. 경매는 추후 유저 100명이상시 사용 예정

2. 테마는 고급스러운 미술경매장 테마

**Comment by ghk829** [comment]
1. ㅇㅋ

2. https://demos.creative-tim.com/material-dashboard-pro/examples/dashboard.html?_ga=2.81938262.1925735549.1535821424-1455348096.1535821424#pablo
이거 어떤지?

**Comment by samslow** [comment]
오 맨밑에 사진이랑 설명 나와있는부분 나은데? 이거 무료야?

**Comment by ghk829** [comment]
무료아님 ㅠ 일단 서비스 페이지 구성하고나서 테마쓸 지 생각해보자.
UI에 자신있으면 직접 만들어도 되고

**Comment by samslow** [comment]
https://github.com/sociablesasha/SHOP-Template.git

여기 참고하자
